import Image from "next/image";
import Link from "next/link";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/homepage/site-footer";
import styles from "./market-pages.module.css";

type Detail = { slug: string; eyebrow: string; title: string; description: string; image: string; intro: string; challenges: string[]; support: string[]; approach: string[]; areas: string[]; related: string[]; enquiry: string; cta: string };

export const services: Detail[] = [
  { slug: "executive-search", eyebrow: "EXECUTIVE SEARCH", title: "Executive Search for Leadership That Moves Organisations Forward.", description: "Crestavia supports organisations making critical executive appointments, with a rigorous and thoughtful approach to finding leaders aligned to the mandate and the moment.", image: "/images/hero/hero-executive-leadership.png", intro: "A senior appointment can influence strategy, culture and performance for years to come. We help organisations define the leadership required, examine the relevant market and engage executives with care and discretion.", challenges: ["A pivotal C-suite or senior leadership vacancy", "A succession-driven appointment", "A confidential search or sensitive transition", "An international or cross-market leadership requirement"], support: ["Clarifying the mandate, leadership context and success profile", "Mapping relevant leadership markets and communities", "Confidential candidate engagement and evaluation", "Shortlisting, alignment and appointment support"], approach: ["Understand the organisation and appointment", "Map and research the leadership market", "Engage and assess relevant executives", "Support decisions through shortlist and appointment"], areas: ["Chief Executive, Finance and Operating Officers", "Technology, digital and information leadership", "People, commercial and growth leadership", "Operations, manufacturing and specialist functions", "Regional and international leadership"], related: ["Aerospace & Defence", "Industrial & Manufacturing", "Technology & Digital", "Financial Services"], enquiry: "executive-search", cta: "Discuss an Executive Search" },
  { slug: "board-advisory", eyebrow: "BOARD ADVISORY", title: "Strengthening Boards for the Decisions Ahead.", description: "Crestavia helps organisations consider the board capability, perspective and leadership needed for consequential decisions and changing strategic priorities.", image: "/images/hero/hero-board-advisory.png", intro: "Boards face evolving expectations around composition, succession and the breadth of perspective required to oversee complex organisations. We provide search and advisory support focused on the leadership requirement at hand; we do not provide legal governance advice.", challenges: ["A board appointment or planned succession", "A need for independent or non-executive perspective", "A changing strategic, market or stakeholder context", "A committee or specialist adviser requirement"], support: ["Board composition and capability discussions", "Board Director, Chair and non-executive searches", "Succession-oriented market insight", "Identification of strategic advisers with relevant experience"], approach: ["Clarify the strategic requirement and context", "Define the experience and perspective sought", "Map relevant leadership communities", "Engage candidates and support an informed decision"], areas: ["Board Directors and Independent Directors", "Non-Executive Directors", "Board Chairs where relevant", "Committee capability", "Specialist strategic advisers"], related: ["Financial Services", "Healthcare & Life Sciences", "Energy & Sustainability", "Technology & Digital"], enquiry: "board-advisory", cta: "Discuss a Board Requirement" },
  { slug: "leadership-advisory", eyebrow: "LEADERSHIP ADVISORY", title: "Leadership Insight for Moments of Change.", description: "Crestavia supports organisations considering leadership capability, succession and alignment as business priorities, teams and operating models evolve.", image: "/images/hero/hero-global-search.png", intro: "Growth, transformation and transition can expose new leadership requirements. Our advisory work brings structured perspective to the decisions organisations make about leadership teams, individual executives and what is needed next.", challenges: ["A planned leadership transition", "A succession planning priority", "A leadership team navigating growth or transformation", "A need to clarify future organisational leadership requirements"], support: ["Succession planning conversations", "Executive assessment informed by role context", "Leadership team capability and alignment", "Executive transition and future-leadership perspective"], approach: ["Understand the organisational moment", "Define the leadership questions to address", "Bring relevant assessment and market perspective", "Translate insight into clear next steps"], areas: ["Succession and transition", "Executive assessment", "Leadership team effectiveness", "Organisational transformation", "Future leadership requirements"], related: ["Industrial & Manufacturing", "Technology & Digital", "Healthcare & Life Sciences", "Energy & Sustainability"], enquiry: "leadership-advisory", cta: "Discuss Your Leadership Priorities" },
  { slug: "talent-intelligence", eyebrow: "TALENT INTELLIGENCE", title: "Better Leadership Decisions Begin with Better Intelligence.", description: "Crestavia provides market-informed perspective to help organisations understand leadership landscapes before, alongside or beyond a search.", image: "/images/hero/hero-global-search.png", intro: "Leadership decisions benefit from a clearer view of the relevant market. We develop focused intelligence around talent availability, competitor landscapes and emerging capability needs, tailored to the business question rather than presented as a generic dataset.", challenges: ["An uncertain executive talent market", "A need to compare leadership availability across markets", "A succession or workforce planning question", "A changing competitive or capability landscape"], support: ["Executive market mapping", "Competitor leadership landscape reviews", "Leadership benchmarking and availability perspective", "Succession intelligence and emerging capability insight"], approach: ["Frame the business question", "Define the relevant market and comparison set", "Research available leadership signals", "Present practical, decision-ready insight"], areas: ["Market mapping", "Competitor talent landscapes", "Leadership benchmarking", "Location and market comparisons", "Emerging leadership capabilities"], related: ["Technology & Digital", "Financial Services", "Energy & Sustainability", "Aerospace & Defence"], enquiry: "talent-intelligence", cta: "Discuss a Talent Intelligence Requirement" },
];

export const sectors: Detail[] = [
  { slug: "aerospace-defence", eyebrow: "AEROSPACE & DEFENCE", title: "Leadership for Complex Aerospace and Defence Environments.", description: "Crestavia brings a measured, market-aware approach to leadership questions in aerospace, aviation, defence and advanced engineering environments.", image: "/images/homepage/aerospace.jpg", intro: "Organisations in this sector navigate long investment cycles, technical complexity, supply-chain resilience and evolving technology priorities. Leadership requirements often combine operational depth with strategic judgement and an ability to work across demanding stakeholder environments.", challenges: ["Technology and engineering change", "Operational resilience and supply-chain pressure", "International growth and programme complexity", "Succession in specialist leadership roles"], support: ["Executive and specialist leadership search", "Board and advisory requirements", "Leadership succession and capability discussions", "Targeted talent-market intelligence"], approach: ["Understand the operating context", "Define the leadership capability required", "Map relevant specialist markets", "Support engagement and decision-making"], areas: ["Aerospace manufacturing", "Aviation and MRO", "Space and satellite", "Defence technology", "Advanced engineering"], related: ["Executive Search", "Board Advisory", "Leadership Advisory", "Talent Intelligence"], enquiry: "executive-search", cta: "Discuss Your Leadership Requirement" },
  { slug: "industrial-manufacturing", eyebrow: "INDUSTRIAL & MANUFACTURING", title: "Leadership for Industry in Motion.", description: "Crestavia supports industrial and manufacturing organisations as they strengthen leadership for operational performance, technology change and long-term growth.", image: "/images/homepage/manufacturing.jpg", intro: "Industrial businesses are balancing productivity, automation, supply-chain dynamics and changing customer expectations. Effective leaders need to connect operational reality with investment, talent and strategic direction.", challenges: ["Operational transformation", "Manufacturing and supply-chain leadership", "Automation and industrial technology adoption", "Succession in specialist functional roles"], support: ["Executive appointments across operations and functions", "Leadership assessment and transition perspective", "Board capability discussions", "Industrial talent-market mapping"], approach: ["Build an informed view of the business", "Clarify the leadership outcome", "Identify relevant industrial talent pools", "Engage leaders with context and discretion"], areas: ["Advanced manufacturing", "Industrial technology", "Engineering", "Automotive and mobility", "Supply chain and operations"], related: ["Executive Search", "Leadership Advisory", "Talent Intelligence", "Board Advisory"], enquiry: "executive-search", cta: "Discuss Your Leadership Requirement" },
  { slug: "technology-digital", eyebrow: "TECHNOLOGY & DIGITAL", title: "Leadership for Technology-Led Change.", description: "Crestavia helps organisations consider the leadership needed to build, transform and govern technology-enabled businesses.", image: "/images/homepage/technology.jpg", intro: "Technology and digital leadership demands are changing quickly as organisations address product, platforms, data, AI, security and enterprise transformation. We help define and search for leadership capability in the context of the organisation’s actual priorities.", challenges: ["Digital transformation and modernisation", "Data, AI and cybersecurity leadership", "Scaling software and platform organisations", "Technology succession and capability gaps"], support: ["Executive search for technology and digital leaders", "Market mapping and competitor landscape insight", "Leadership advisory for transition and growth", "Board and strategic technology perspective"], approach: ["Understand the technology and business agenda", "Define capability, scale and leadership fit", "Map relevant digital talent markets", "Support focused engagement and assessment"], areas: ["Enterprise technology", "Software", "Digital transformation", "Data and AI leadership", "Cybersecurity and cloud infrastructure"], related: ["Executive Search", "Talent Intelligence", "Leadership Advisory", "Board Advisory"], enquiry: "executive-search", cta: "Discuss Your Leadership Requirement" },
  { slug: "healthcare-life-sciences", eyebrow: "HEALTHCARE & LIFE SCIENCES", title: "Leadership for Healthcare and Life Sciences Progress.", description: "Crestavia supports leadership decisions in organisations working across healthcare, life sciences, technology and operational delivery.", image: "/images/homepage/healthcare.jpg", intro: "Healthcare and life sciences organisations operate at the intersection of science, commercial execution, patient outcomes and complex regulation. Leadership teams must bring specialist understanding while navigating constant innovation and change.", challenges: ["Scientific, technical and commercial leadership needs", "Growth and operating-model change", "Leadership succession in specialist functions", "Talent availability across competitive markets"], support: ["Executive and board search", "Leadership assessment and transition support", "Specialist market mapping", "Succession and organisational leadership perspective"], approach: ["Understand the organisation’s scientific and business context", "Define the leadership requirement", "Identify relevant sector and functional markets", "Support a thoughtful appointment process"], areas: ["Pharmaceuticals", "Biotechnology", "Medical technology", "Healthcare services", "Manufacturing, operations and research leadership"], related: ["Executive Search", "Board Advisory", "Leadership Advisory", "Talent Intelligence"], enquiry: "executive-search", cta: "Discuss Your Leadership Requirement" },
  { slug: "financial-services", eyebrow: "FINANCIAL SERVICES", title: "Leadership for Evolving Financial Services.", description: "Crestavia supports executive and board leadership decisions across financial services as organisations respond to new technologies, customer expectations and market dynamics.", image: "/images/homepage/financial.jpg", intro: "Financial services businesses must balance commercial ambition, operational resilience, innovation and complex stakeholder expectations. The right leadership perspective is essential as models, markets and customer relationships evolve.", challenges: ["Digital and business-model change", "Board composition and leadership succession", "Specialist functional leadership requirements", "Competitive talent landscapes"], support: ["Executive and non-executive appointments", "Board advisory and composition perspective", "Leadership assessment and succession support", "Talent intelligence and market mapping"], approach: ["Clarify the business and leadership context", "Define relevant expertise and perspective", "Map leadership communities", "Support confidential engagement and selection"], areas: ["Banking", "Payments and fintech", "Insurance", "Investment and asset-management environments", "Digital financial services"], related: ["Executive Search", "Board Advisory", "Talent Intelligence", "Leadership Advisory"], enquiry: "executive-search", cta: "Discuss Your Leadership Requirement" },
  { slug: "energy-sustainability", eyebrow: "ENERGY & SUSTAINABILITY", title: "Leadership for the Energy Transition and Beyond.", description: "Crestavia helps energy, infrastructure and sustainability-oriented organisations assess the leadership needed for investment, transformation and long-term progress.", image: "/images/homepage/energy.jpg", intro: "The sector is shaped by infrastructure demands, changing technologies, investment decisions and the transition to lower-carbon models. Leadership teams need to bring operational depth alongside the ability to navigate evolving markets and strategic priorities.", challenges: ["Energy transition and portfolio change", "Infrastructure and project leadership", "New technology and capability needs", "Succession in specialist and senior roles"], support: ["Executive and board appointments", "Leadership advisory for transformation", "Targeted market and talent intelligence", "Succession and capability conversations"], approach: ["Understand the market and organisational context", "Define leadership outcomes", "Map relevant energy and infrastructure markets", "Support informed engagement and appointment"], areas: ["Conventional and transition energy", "Renewable energy", "Clean technology", "Infrastructure and utilities", "Sustainability-oriented businesses"], related: ["Executive Search", "Leadership Advisory", "Talent Intelligence", "Board Advisory"], enquiry: "executive-search", cta: "Discuss Your Leadership Requirement" },
];

export function DetailPage({ detail, kind }: { detail: Detail; kind: "service" | "sector" }) {
  const relatedHref = kind === "service" ? "/sectors" : "/services";
  const sectionName = kind === "service" ? "Services" : "Sectors";
  const sectionPath = kind === "service" ? "services" : "sectors";
  const breadcrumbs = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home", item: "https://crestaviaexecutivepartners.org/" },
      { "@type": "ListItem", position: 2, name: sectionName, item: `https://crestaviaexecutivepartners.org/${sectionPath}` },
      { "@type": "ListItem", position: 3, name: detail.eyebrow, item: `https://crestaviaexecutivepartners.org/${sectionPath}/${detail.slug}` },
    ],
  };
  return <div id="top"><SiteHeader /><main>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbs) }} />
    <section className={styles.hero}><div className={styles.container + " " + styles.heroGrid}><div><p className={styles.eyebrow}>{detail.eyebrow}</p><h1>{detail.title}</h1><p>{detail.description}</p><Link className={styles.redButton} href={`/contact?enquiry=${detail.enquiry}`} prefetch={false}>{detail.cta} <span>→</span></Link></div><div className={styles.heroImage}><Image src={detail.image} alt="" fill priority sizes="(max-width: 700px) 100vw, 48vw" /></div></div></section>
    <section className={styles.intro}><div className={styles.narrow}><p className={styles.eyebrow}>THE CONTEXT</p><h2>Perspective for consequential leadership decisions.</h2><p>{detail.intro}</p></div></section>
    <section className={styles.split}><div className={styles.container + " " + styles.splitGrid}><article><p className={styles.eyebrow}>WHEN IT MATTERS</p><h2>Situations where focused support can help.</h2><List items={detail.challenges} /></article><article><p className={styles.eyebrow}>HOW WE SUPPORT</p><h2>Practical perspective, tailored to the requirement.</h2><List items={detail.support} /></article></div></section>
    <section className={styles.method}><div className={styles.container}><p className={styles.eyebrow}>OUR APPROACH</p><h2>A disciplined process, informed by context.</h2><ol>{detail.approach.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span><p>{item}</p></li>)}</ol></div></section>
    <section className={styles.areas}><div className={styles.container + " " + styles.areasGrid}><div><p className={styles.eyebrow}>{kind === "service" ? "RELEVANT LEADERSHIP AREAS" : "AREAS OF FOCUS"}</p><h2>Experience that reflects the environment.</h2></div><List items={detail.areas} /></div></section>
    <section className={styles.related}><div className={styles.container}><p className={styles.eyebrow}>RELATED {kind === "service" ? "SECTORS" : "SERVICES"}</p><div className={styles.tagList}>{detail.related.map((item) => <Link key={item} href={relatedHref} prefetch={false}>{item} <span>→</span></Link>)}</div></div></section>
    <section className={styles.closing}><div className={styles.container}><p className={styles.eyebrow}>START A CONVERSATION</p><h2>The right leadership decision can shape what comes next.</h2><Link className={styles.redButton} href={`/contact?enquiry=${detail.enquiry}`} prefetch={false}>{detail.cta} <span>→</span></Link></div></section>
  </main><SiteFooter /></div>;
}

function List({ items }: { items: string[] }) { return <ul className={styles.list}>{items.map((item) => <li key={item}>{item}</li>)}</ul>; }
