"use client";

import Link from "next/link";
import { useEffect, useRef, useState, useSyncExternalStore, type FormEvent, type ReactNode } from "react";
import styles from "./site-experiences.module.css";

const consentKey = "crestavia-cookie-consent";
const choices = [["Hire Executive Talent", "/contact?enquiry=executive-search"], ["Board / Advisory Requirement", "/contact?enquiry=board-advisory"], ["Leadership Advisory", "/contact?enquiry=leadership-advisory"], ["Talent Intelligence", "/contact?enquiry=talent-intelligence"], ["Explore Executive Opportunities", "/careers"], ["General Enquiry", "/contact?enquiry=general"]] as const;

function subscribeToConsent(onStoreChange: () => void) { window.addEventListener("storage", onStoreChange); window.addEventListener("crestavia-consent-change", onStoreChange); return () => { window.removeEventListener("storage", onStoreChange); window.removeEventListener("crestavia-consent-change", onStoreChange); }; }
function readConsent() { return window.localStorage.getItem(consentKey) ?? ""; }
function serverConsent() { return ""; }
function parseConsent(value: string) { try { const parsed: unknown = JSON.parse(value); if (typeof parsed === "object" && parsed !== null) { const record = parsed as Record<string, unknown>; return { analytics: record.analytics === true, marketing: record.marketing === true }; } } catch { /* Invalid historical data is treated as no saved preference. */ } return { analytics: false, marketing: false }; }

export function ContactChooser({ children, className = "" }: { children: ReactNode; className?: string }) { const [open, setOpen] = useState(false); const dialog = useRef<HTMLDivElement>(null); useEffect(() => { if (!open) return; const prior = document.activeElement as HTMLElement; dialog.current?.querySelector<HTMLElement>("a,button")?.focus(); const key = (e: KeyboardEvent) => { if (e.key === "Escape") setOpen(false); }; document.addEventListener("keydown", key); return () => { document.removeEventListener("keydown", key); prior?.focus(); }; }, [open]); return <><button type="button" className={className} onClick={() => setOpen(true)}>{children}</button>{open && <div className={styles.backdrop} onMouseDown={() => setOpen(false)}><div ref={dialog} className={styles.dialog} role="dialog" aria-modal="true" aria-labelledby="contact-choice-title" onMouseDown={(e) => e.stopPropagation()}><button className={styles.close} type="button" onClick={() => setOpen(false)} aria-label="Close contact options">×</button><p>CONTACT CRESTAVIA</p><h2 id="contact-choice-title">Choose the right conversation.</h2><div>{choices.map(([label, href]) => <Link key={href} href={href} prefetch={false} onClick={() => setOpen(false)}>{label}<span>→</span></Link>)}</div></div></div>}</>; }

export function NewsletterForm() { const [state, setState] = useState<"idle" | "loading" | "error">("idle"); function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setState("loading"); window.setTimeout(() => setState("error"), 350); } return <form className={styles.newsletter} onSubmit={submit}><label htmlFor="newsletter-email">Email address</label><div><input id="newsletter-email" type="email" required autoComplete="email" placeholder="Your email address" /><button disabled={state === "loading"}>{state === "loading" ? "…" : "→"}</button></div><small>By subscribing, you agree to receive Crestavia leadership insights. You can unsubscribe at any time.</small><p role="status">{state === "error" ? "Newsletter subscriptions are not connected yet. Please try again later." : ""}</p></form>; }

export function CookieConsent() { const persisted = useSyncExternalStore(subscribeToConsent, readConsent, serverConsent); const saved = persisted.length > 0; const stored = parseConsent(persisted); const [open, setOpen] = useState(false); const [analytics, setAnalytics] = useState(false); const [marketing, setMarketing] = useState(false); useEffect(() => { const reopen = () => { setAnalytics(stored.analytics); setMarketing(stored.marketing); setOpen(true); }; window.addEventListener("crestavia-open-cookie-preferences", reopen); return () => window.removeEventListener("crestavia-open-cookie-preferences", reopen); }, [stored.analytics, stored.marketing]); const save = (nextAnalytics: boolean, nextMarketing: boolean) => { window.localStorage.setItem(consentKey, JSON.stringify({ essential: true, analytics: nextAnalytics, marketing: nextMarketing })); window.dispatchEvent(new Event("crestavia-consent-change")); setOpen(false); }; const manage = () => { setAnalytics(stored.analytics); setMarketing(stored.marketing); setOpen(true); }; if (saved && !open) return null; return <div className={styles.cookie} role="dialog" aria-modal="true" aria-labelledby="cookie-title"><h2 id="cookie-title">{open ? "Cookie preferences" : "Your privacy choices"}</h2><p>Essential cookies keep this site working. Analytics and marketing are optional; no analytics or marketing trackers are currently active.</p>{open && <fieldset><legend>Optional categories</legend><label><input type="checkbox" checked={analytics} onChange={(e) => setAnalytics(e.target.checked)} /> Analytics</label><label><input type="checkbox" checked={marketing} onChange={(e) => setMarketing(e.target.checked)} /> Marketing</label></fieldset>}<div><button type="button" onClick={() => save(true, true)}>Accept All</button><button type="button" onClick={() => save(false, false)}>Reject Optional</button>{!open && <button type="button" onClick={manage}>Manage Preferences</button>}{open && <button type="button" onClick={() => save(analytics, marketing)}>Save Preferences</button>}</div></div>; }

export function CookiePreferencesButton() { return <button type="button" className={styles.cookieLink} onClick={() => window.dispatchEvent(new Event("crestavia-open-cookie-preferences"))}>Cookie Preferences</button>; }
