"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { Brand } from "./brand";
import styles from "./site-header.module.css";

const navigation = [{ label: "Home", href: "/" }, { label: "About", href: "/about" }, { label: "Our Services", href: "/services" }, { label: "Sectors", href: "/sectors" }, { label: "Insights", href: "/insights" }, { label: "Careers", href: "/careers" }, { label: "Contact", href: "/contact" }] as const;
function ArrowIcon() { return <svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 12h14m-6-6 6 6-6 6" /></svg>; }
export function SiteHeader() { const pathname = usePathname(); const [open, setOpen] = useState(false); const headerRef = useRef<HTMLElement>(null); const menuButtonRef = useRef<HTMLButtonElement>(null); useEffect(() => { if (!open) return; const onKeyDown = (event: KeyboardEvent) => { if (event.key === "Escape") { setOpen(false); menuButtonRef.current?.focus(); } }; const onPointerDown = (event: PointerEvent) => { if (event.target instanceof Node && !headerRef.current?.contains(event.target)) setOpen(false); }; document.addEventListener("keydown", onKeyDown); document.addEventListener("pointerdown", onPointerDown); return () => { document.removeEventListener("keydown", onKeyDown); document.removeEventListener("pointerdown", onPointerDown); }; }, [open]); const links = navigation.map(({ label, href }) => <li key={href}><Link href={href} prefetch={false} className={styles.navLink} aria-current={(href === "/" ? pathname === href : pathname.startsWith(href)) ? "page" : undefined} onClick={() => setOpen(false)}>{label}</Link></li>); return <header className={styles.header} ref={headerRef}><div className={styles.inner}><Brand /><nav className={styles.desktopNav} aria-label="Primary navigation"><ul>{links}</ul></nav><div className={styles.actions}><Link className={styles.contactButton} href="/contact" prefetch={false}><span>Get in Touch</span><ArrowIcon /></Link><button className={styles.iconButton + " " + styles.menuButton} type="button" ref={menuButtonRef} aria-label={open ? "Close menu" : "Open menu"} aria-expanded={open} aria-controls="header-panel" onClick={() => setOpen(!open)}><span className={styles.menuLines} data-open={open} aria-hidden="true"><span /><span /><span /></span></button></div></div><div id="header-panel" className={styles.panel} hidden={!open}><nav aria-label="Expanded navigation"><ul className={styles.panelLinks}>{links}</ul></nav></div></header>; }
